spring:
  http:
    encoding:
      charset: UTF-8
  mvc:
    servlet:
      load-on-startup: 1
  kafka:
    producer:
      bootstrap-servers: "localhost:9092"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
    consumer:
      bootstrap-servers: "localhost:9092"
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "com.hch.pojo"
    listener:
      ack-mode: manual


#  datasource:
#    url: jdbc:MySQL://hch-cloud:3306/test?characterEncoding=utf8&autoReconnect=true&&useSSL=false&&allowPublicKeyRetrieval=True
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 1
#      connection-timeout: 5000
#      idle-timeout: 5000
#    type: com.alibaba.druid.pool.DruidDataSource

redis:
  server: "localhost:6379"

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: 'classpath:com/hch/dao/mapper/*.xml'

server:
  servlet:
    context-path: /api/sbp/v1/
  tomcat:
    max-threads: 32
    accept-count: 1
    max-connections: 8000
#    min-spare-threads: 1
#  connection-timeout: 5000

custom:
  projectName: springboot-practice
  author:
    name: "张三"
    age: 18
    birthday: 2019/5/18
    male: true

logging:
  level:
    com.hch: debug
