spring:
#  http:
#    encoding:
#      charset: UTF-8
#  mvc:
#    servlet:
#      load-on-startup: 1
#  datasource:
#    url: jdbc:h2:file:./local-test-h2;MODE=MYSQL
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#  servlet:
#    multipart:
#      max-file-size: 10GB
#      max-request-size: 20GB
  redis:
    host: hch-ubuntu.local # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间
#    lettuce:
#      pool:
#        max-active: 8 # 连接池最大连接数
#        max-idle: 8 # 连接池最大空闲连接数
#        min-idle: 0 # 连接池最小空闲连接数
#        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制

server:
  servlet:
    context-path: /api/sbp/v1/
  tomcat:
    max-threads: 1
#    accept-count: 1
#    max-connections: 1
#    min-spare-threads: 1
  connection-timeout: 5000

custom:
  projectName: springboot-practice
  author:
    name: "hch"
    age: 18
    birthDay: 2019/5/18
    male: true

